# Generated by Django 3.2.5 on 2021-12-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(max_length=100)),
                ('experience_Post', models.CharField(max_length=100)),
                ('experience_description', models.EmailField(max_length=254)),
                ('experience_img', models.ImageField(upload_to='experience/')),
            ],
            options={
                'verbose_name': 'Experience',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
