# Generated by Django 3.2.5 on 2021-12-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_auto_20211226_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='experience_description',
            field=models.TextField(),
        ),
    ]
