# Generated by Django 3.1.7 on 2021-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_auto_20211210_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_image',
            field=models.ImageField(default='', upload_to='skill/'),
            preserve_default=False,
        ),
    ]
