# Generated by Django 3.1.7 on 2021-12-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_skills_skill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill_image',
        ),
    ]
