# Generated by Django 3.2.5 on 2021-12-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_alter_experiences_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_img',
            field=models.ImageField(default='', upload_to='skil_img/'),
            preserve_default=False,
        ),
    ]
