# Generated by Django 3.1.7 on 2021-12-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_remove_skills_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfoliomessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
