# Generated by Django 3.2.5 on 2021-12-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_skills_skill_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill_img',
        ),
        migrations.AddField(
            model_name='experiences',
            name='link',
            field=models.URLField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
