# Generated by Django 3.1.7 on 2021-12-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_porfoliomessage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porfoliomessage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='porfoliomessage',
            name='date',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='porfoliomessage',
            name='time',
            field=models.CharField(default='', max_length=12),
        ),
    ]
