# Generated by Django 3.1.7 on 2021-12-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_auto_20211211_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porfoliomessage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='porfoliomessage',
            name='time',
        ),
        migrations.AddField(
            model_name='porfoliomessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
