# Generated by Django 3.1.7 on 2021-12-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_auto_20211211_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfoliomessage',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
